#!/bin/bash
./stem.sh SuzieQ CCR 
./stem.sh "Emminence front" Who
./stem.sh "I melt with you" "Modern English"
./stem.sh "Bad Moon Rising" "CCR"
./stem.sh "These boots are made for walk" "nancy sinatra"
./stem.sh "Come Together" "Beatles"
./stem.sh "Dreams" "Fleetwood Mac"
./stem.sh "While my guitar gently weeps" "Beatles"
./stem.sh "Whip It" "Devo"
./stem.sh "Slave" "Rolling Stones"
./stem.sh "Dont bring me down" "Beattles"
./stem.sh "Ramblin Man" "Allman Brothers"
./stem.sh "Take a walk on the wild side" "Lou Reed"
./stem.sh "Life during war time" "Talking Heads"
./stem.sh "Psycho Killer" "Talking Heads"
./stem.sh "Cant let go" "Robert Plant"
./stem.sh "Folsum Prison blues" "Johnny Cash"
./stem.sh "Wild Night" "Van Morrison"
./stem.sh "Come Together" "Beatles"
./stem.sh "Rock and Roll" "Led Zeppelin"
#
./stem.sh "Ramblin man" "allman brothers"
./stem.sh "money" "pink floyd"
./stem.sh "whip it" "devo"
./stem.sh "cars" "gary numan"
./stem.sh "spooky" "atlanta rythem section"
./stem.sh "Thank You" "Led Zeppelin"
./stem.sh "Hey Hey" "Led Zeppelin"
./stem.sh "Black Dog" "Led Zeppelin"
./stem.sh "Seventeen" "Stevie Nicks"
./stem.sh "Middle of the Road" "Pretenders"
./stem.sh "Mystery Acheivement" "Pretenders"
./stem.sh "Brass in Pocket" "Pretenders"
#./stem.sh "" ""
./stem.sh "Ramble On" "Led Zeppelin"
./stem.sh "Good Times Bad Times" "Led Zeppelin"
./stem.sh "Good Love" "Lovin Spoonful"

./stem.sh "Freebird" "Lynryd Skynyrd"
./stem.sh "Friend of the Devil" "Grateful Dead"
./stem.sh "Get Up Stand Up" "Bob Marley"
./stem.sh "Gimme Shelter" "Rolling Stones"
./stem.sh "Going up the Country" "Canned Heat"
./stem.sh "Hard to Handle" "Black Crows"
#
#./stem.sh "" ""

